# Yarn 4 configuration for Cloudflare Workers deployment
# Disable lockfile validation to allow dependency installation
enableImmutableInstalls: false

# Use node-modules linker for better compatibility
nodeLinker: node-modules

# Disable telemetry
enableTelemetry: false